name: Build and Release Binary

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Get version and name
        id: package_info
        run: |
          echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"
          echo "::set-output name=NAME::$(node -p "require('./package.json').name")"

      - name: Build binary with pkg
        run: |
          pkg ./src/Executables/exec-pkg.js --targets node18-linux-x64 --output ${{ steps.package_info.outputs.NAME }}-${{ steps.package_info.outputs.VERSION }}-preview-linux-x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: ${{ steps.package_info.outputs.NAME }}-${{ steps.package_info.outputs.VERSION }}-preview-linux-x64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/${{ needs.build.outputs.NAME }}-${{ needs.build.outputs.VERSION }}-preview-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
