name: Build and Release Binary

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install PKG globally
        run: npm install -g pkg

      - name: Get version and name
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: Build binary with pkg
        run: |
          pkg ./src/Executables/exec-pkg.js --targets node18-linux-x64 --output ${{ env.NAME }}-${{ env.VERSION }}-preview-linux-x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: ${{ env.NAME }}-${{ env.VERSION }}-preview-linux-x64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Create or update tag
        run: |
          git fetch --tags
          git tag -fa ${{ env.VERSION }} -m "Update tag ${{ env.VERSION }}"
          git push origin ${{ env.VERSION }} --force

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ env.NAME }}-${{ env.VERSION }}-preview-linux-x64
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
